# Start from the Kali base image
FROM kalilinux/kali-rolling

# Install utils
#nmap, ping, iproute2, wafw00f, wget
RUN apt update && \
    # apt -y install kali-linux-headless && \
    apt install inetutils-ping -y && \
    apt install nmap -y && \
    apt install iproute2 -y && \
    apt install wafw00f -y && \ 
    apt install netcat-traditional -y && \
    apt -y install wget 


# The default command for Alpine is to run a shell, which is perfect.
CMD ["/bin/sh"]